### ISSUE TITLE
Strict Notice error

### ISSUE THREAD

**Issue by sanderha** [micschk/silverstripe-latlongfield#1]
I used composer to install the module. Afterwards I then tried to create the latlongfield with: 
$fields->addFieldsToTab('Root.Address', LatLongField::create('Street'));

This gave me the following error in the cms, when loading the page: 

[Strict Notice] Declaration of LatLongField::FieldHolder() should be compatible with FormField::FieldHolder($properties = Array)

When I tried to type in an adress and search, it also returns 'ZERO_RESULTS'.

Any ideas? Besides this, it seems like a pretty awesome module

**Comment by sanderha** [comment]
I changed public function FieldHolder() to public function FieldHolder($properties = array()) instead, which got rid of the error

**Comment by micschk** [comment]
Thanks for the tip, fixed now.
